# Generated by Django 3.2.5 on 2022-07-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210830_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='Painting_Id',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='Quantity',
        ),
        migrations.AddField(
            model_name='artwork',
            name='img',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artwork',
            name='Painting_Title',
            field=models.CharField(max_length=100),
        ),
    ]
