# Generated by Django 3.2.5 on 2022-07-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220719_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='price',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artwork',
            name='size',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
